config/routes.rb
BookerApp::Application.routes.draw do
  resources :recommendations

root :to => "home#index"

end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  # GET /recommendations
  # GET /recommendations.xml
  def index
    @recommendations = Recommendation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @recommendations }
    end
  end

  # GET /recommendations/1
  # GET /recommendations/1.xml
  def show
    @recommendation = Recommendation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recommendation }
    end
  end

  # GET /recommendations/new
  # GET /recommendations/new.xml
  def new
    @recommendation = Recommendation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recommendation }
    end
  end

  # GET /recommendations/1/edit
  def edit
    @recommendation = Recommendation.find(params[:id])
  end

  # POST /recommendations
  # POST /recommendations.xml
  def create
    @recommendation = Recommendation.new(params[:recommendation])

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to(@recommendation, :notice => 'Recommendation was successfully created.') }
        format.xml  { render :xml => @recommendation, :status => :created, :location => @recommendation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recommendation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recommendations/1
  # PUT /recommendations/1.xml
  def update
    @recommendation = Recommendation.find(params[:id])

    respond_to do |format|
      if @recommendation.update_attributes(params[:recommendation])
        format.html { redirect_to(@recommendation, :notice => 'Recommendation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recommendation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.xml
  def destroy
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy

    respond_to do |format|
      format.html { redirect_to(recommendations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/home/index.html.erb
<h1>Tämä on bookerin etusivu</h1>
<%= link_to "Suositukset", recommendations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookerApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recommendations/_form.html.erb
<%= form_for(@recommendation) do |f| %>
  <% if @recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
      <% @recommendation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Myyja %><br />
    <%= f.text_field :salesrep %>
  </div>
  <div class="field">
    <%= f.label :Asiakas %><br />
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :Sukunimi %><br />
    <%= f.text_field :sukunimi %>
  </div>
  <div class="field">
    <%= f.label :Kauppa_ok? %><br />
    <%= f.check_box :saleagreed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recommendations/edit.html.erb
<h1>Muokkaa suosituksia</h1>

<%= render 'form' %>

<%= link_to 'Show', @recommendation %> |
<%= link_to 'Back', recommendations_path %>

app/views/recommendations/index.html.erb
<h1>Lista suosituksista</h1>

<table>
  <tr>
    <th>Edustaja</th>
    <th>Asiakas</th>
	<th>Sukunimi</th>
    <th>Kauppa tehty?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recommendations.each do |recommendation| %>
<% if recommendation.saleagreed %>
	<% tulos = "YES!" else tulos = "Ei ole onnistanut (:" %>
<% end %>
  <tr>
    <td><%= recommendation.salesrep %></td>
    <td><%= recommendation.customer %></td>
    <td><%= recommendation.sukunimi %></td>
    <td><%= tulos %></td>
    <td><%= link_to 'Show', recommendation %></td>
    <td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
    <td><%= link_to 'Destroy', recommendation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Uusi suositus', new_recommendation_path %>

app/views/recommendations/new.html.erb
<h1>Uusi suositus, ole hyvä</h1>

<%= render 'form' %>

<%= link_to 'Back', recommendations_path %>

app/views/recommendations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Salesrep:</b>
  <%= @recommendation.salesrep %>
</p>

<p>
  <b>Customer:</b>
  <%= @recommendation.customer %>
</p>

<p>
  <b>Sukunimi:</b>
  <%= @recommendation.sukunimi %>
</p>

<p>
  <b>Saleagreed:</b>
  <%= @recommendation.saleagreed %>
</p>


<%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
<%= link_to 'Back', recommendations_path %>